### ISSUE TITLE
Different order of catagories page 

### ISSUE THREAD

**Issue by tatecarson** [jake-101/bael-template#18]
Hello, 

Is it possible to order the categories page in a way other than alphabetical? I am looking through the code and can't figure out where I would do it. I was thinking of adding an order property to each category JSON but am not sure what to do with it after that.

**Comment by tatecarson** [comment]
I actually am not using the template for a blog so it might be an odd use case. I wanted the categories on my [site](https://tatecarson.com) to be in order of importance. I couldn't figure out a better solution so I just [reversed the array](https://github.com/tatecarson/tatecarson-new-new/blob/cc13e5d73b7b8d9ae65464f1ce77924a7204bf70/components/BaelGrid.vue#L69) and it happened to be what I needed. Being able to give each category a custom order or at least weight (like Hugo does) would have been helpful. Looking forward to the refactor and thanks for making such a great looking and performing template!

**Comment by jake-101** [comment]
Thanks for your input and for using it! Your feedback will be included in the next update.
