### ISSUE TITLE
Email signup seems to be broken or missing some setup

### ISSUE THREAD

**Issue by s4mur4i** [jake-101/bael-template#2]
Hello,

I deployed your website for testing, and when configuring and enabling email signup nothing happens.
![request](https://user-images.githubusercontent.com/521166/45588261-43a16280-b912-11e8-95cc-f0b2e80af3c9.jpg)
I attached a screenshot of the request I see in developer tools
On netlify console I don't see any new requests comming in.
In app.js logs on netlify console I also see no lines.
Is there some change or setup needed that I missed?

Thank you

**Comment by BRS999** [comment]
I've figured it out!. 

You need to update your code here:

`async processForm() {
      try {
        const sendgrid = await this.$axios.post(
          "YOURDOMAIN/.netlify/functions/app",
          this.emaildata
        );
        console.log("Processed!");
        this.sent = true;
      } catch (e) {
        console.log(e);
      }`

Just add your domain to the string instead of /.netlify/functions/app.

**Comment by jake-101** [comment]
Hi I've added a env variable called API_URL to netlify.toml that will be in the next release. I never really tested the lambdas locally, I always would publish it to Netlify. Thanks for figuring this out!
