### ISSUE TITLE
Future Updates

### ISSUE THREAD

**Issue by suits-at** [jake-101/bael-template#3]
Nice work on this. But this repo hasn't got any updates for quite some time. Will there be any future updates?

**Comment by vallerydelexy** [comment]
also wondering the same thing

**Comment by jake-101** [comment]
Hi @suits-at and @vallerydelexy, I haven't had much time to work on this theme but I just did a few updates. I would love to hear what improvements you would like to see. I think I am going to add a different home page view that shows the featured image and takes up the whole screen.

**Comment by suits-at** [comment]
Hi @jake-101, thanks for the updates. I don't need any other improvements. A current & working example is all I wanted to see.

**Comment by jake-101** [comment]
Great, I'll have to try out your Gridsome / Netlify CMS template. How do you like Gridsome compared to nuxt?

**Comment by suits-at** [comment]
Let me know if it works for you! I am planning to add some more documentation and add it to the netlfify cms templates sometime soon aswell! 
I think its nice for a fast start, but if you want some finetuning I am not sure if its worth it (yet). Gridsome is still in a very early phase and there is still plenty of work to do. So if you are familiar with nuxt, it might be the more straight forward way I guess.
